name: Update sing-tun dep
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          go get github.com/hwsaya/sing-tun@97e9e189002f556742a1e53fbc972692b9ad9078
          go mod tidy
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update sing-tun to custom fork"